"""Scaffold a new cluster inside the eq-cycle submodule's working tree.

Creates the source-root layout the `korea-cluster-relocation` framework expects (a sibling of
`pipeline/`), converts the bundled KP_station_list to per-network station_table CSVs in the
framework's format, writes the cluster module (`pipeline/clusters/<name>.py`), and idempotently
registers the cluster in `pipeline/config.py` (`CLUSTER_NAMES` + `CLUSTER_SRC_DIRS`).

All edits are LOCAL to the submodule working tree — they are not committed from PocketQuake.
"""
from __future__ import annotations

import os
import re
import shutil
from dataclasses import dataclass
from typing import Iterable

import pandas as pd

from pocketquake import EQCYCLE_DIR, STATIONS_KP


# ---------------------------------------------------------------- cluster setup
@dataclass(frozen=True)
class ClusterSpec:
    """Inputs that turn a bare catalog into a registered eq-cycle cluster."""
    name: str                                # e.g. "changnyeong"
    region: str                              # display name, e.g. "Changnyeong"
    catalog_csv: str                         # source CSV (will be copied in)
    epicenter: tuple[float, float]           # (lat, lon)
    region_bounds: tuple[float, float, float, float]  # (lat0, lat1, lon0, lon1)
    src_dir_name: str | None = None          # default: f"{region}_cluster"
    networks: tuple[str, ...] = ("KS",)      # which networks' station tables to generate
    dtct_isolv: int = 1                      # 1 = SVD, 2 = LSQR (large clusters)

    @property
    def src_dir(self) -> str:
        return self.src_dir_name or f"{self.region}_cluster"

    @property
    def src_root(self) -> str:
        return os.path.join(EQCYCLE_DIR, self.src_dir)


# ---------------------------------------------------------- station-table convert
def kp_to_eqcycle_format(kp_csv: str, network: str) -> pd.DataFrame:
    """Convert KP_station_list (network,station,startdate,latitude,longitude,datetime_start) into the
    eq-cycle station-table format (Network,Code,Latitude,Longitude,Elevation) for one network.

    KP_station_list lacks elevation; we fill 0.0 (matches the existing eq-cycle KS_station.csv)."""
    kp = pd.read_csv(kp_csv)
    sub = kp[kp.network == network].copy()
    out = pd.DataFrame({
        "Network":   sub["network"],
        "Code":      sub["station"],
        "Latitude":  sub["latitude"],
        "Longitude": sub["longitude"],
        "Elevation": 0.0,            # KP file has no elevation; matches the eq-cycle convention
    })
    return out.reset_index(drop=True)


# ------------------------------------------------------------------- scaffolding
def scaffold(spec: ClusterSpec) -> str:
    """Create the cluster's source-root directory tree + station tables + catalog. Returns src_root."""
    src_root = spec.src_root

    # 1. directory tree (waveforms_dir is filled later by NECIS)
    for sub in ("event_catalog", "station_table", "kma_waveforms"):
        os.makedirs(os.path.join(src_root, sub), exist_ok=True)

    # 2. copy the catalog into the canonical place the framework reads from
    dst_catalog = os.path.join(src_root, "event_catalog", "event_catalog.csv")
    shutil.copyfile(spec.catalog_csv, dst_catalog)

    # 3. emit per-network station tables in the eq-cycle format
    for net in spec.networks:
        df = kp_to_eqcycle_format(STATIONS_KP, net)
        df.to_csv(os.path.join(src_root, "station_table", f"{net}_station.csv"), index=False)

    return src_root


def write_cluster_module(spec: ClusterSpec) -> str:
    """Write `pipeline/clusters/<name>.py` (the `kma_cluster` factory call). Idempotent.

    Returns the absolute path of the written module."""
    path = os.path.join(EQCYCLE_DIR, "pipeline", "clusters", f"{spec.name}.py")
    src_dir_repr = spec.src_dir
    epi_lat, epi_lon = spec.epicenter
    rb = ", ".join(f"{v}" for v in spec.region_bounds)
    nets_repr = ", ".join(f'"{n}_station.csv"' for n in spec.networks)
    body = f'''"""Cluster config for {spec.region} — auto-generated by PocketQuake."""
from dataclasses import replace
import os

from pipeline import config
from pipeline.clusters._base import kma_cluster


CONFIG = kma_cluster(
    name="{spec.name}",
    region="{spec.region}",
    src_root=os.path.join(config.PROJECT_ROOT, "{src_dir_repr}"),
    epicenter=({epi_lat}, {epi_lon}),
    region_bounds=({rb}),
    station_masters=({nets_repr},),
    dtct_isolv={spec.dtct_isolv},
)

# AI-pick-probability HypoInverse weighting (PocketQuake v1.0.0+ default).
# Set the .phs weight code (column 18) from the PhaseNet+ pick probability instead of
# epicentral-distance bins -- the picker's own confidence is a more direct measure of
# pick quality than distance. To revert to the source-cluster behavior, change to
# `phs_weight_scheme="distance"`.
CONFIG = replace(CONFIG, phs_weight_scheme="probability")
'''
    with open(path, "w") as f:
        f.write(body)
    return path


# --------------------------------------------- register the cluster in config.py
_CLUSTER_NAMES_RE = re.compile(r'^(CLUSTER_NAMES\s*=\s*\()(.*?)(\)\s*)$', re.MULTILINE | re.DOTALL)
_CLUSTER_SRC_DIRS_RE = re.compile(r'^(CLUSTER_SRC_DIRS\s*=\s*\()(.*?)(\)\s*)$', re.MULTILINE | re.DOTALL)


def _has_token(tuple_body: str, token: str) -> bool:
    return f'"{token}"' in tuple_body or f"'{token}'" in tuple_body


def register_cluster(spec: ClusterSpec) -> tuple[bool, bool]:
    """Idempotently append `spec.name` to CLUSTER_NAMES and `spec.src_dir` to CLUSTER_SRC_DIRS
    in the eq-cycle's `pipeline/config.py`. Returns (changed_names, changed_dirs)."""
    cfg_path = os.path.join(EQCYCLE_DIR, "pipeline", "config.py")
    text = open(cfg_path).read()
    new = text
    changed_names = changed_dirs = False

    m = _CLUSTER_NAMES_RE.search(new)
    if m and not _has_token(m.group(2), spec.name):
        inside = m.group(2).rstrip()
        if not inside.rstrip().endswith(","):
            inside = inside + ","
        injected = inside + f' "{spec.name}"'
        new = new[: m.start()] + m.group(1) + injected + m.group(3) + new[m.end():]
        changed_names = True

    m = _CLUSTER_SRC_DIRS_RE.search(new)
    if m and not _has_token(m.group(2), spec.src_dir):
        inside = m.group(2).rstrip()
        if not inside.rstrip().endswith(","):
            inside = inside + ","
        injected = inside + f'\n    "{spec.src_dir}",'
        new = new[: m.start()] + m.group(1) + injected + m.group(3) + new[m.end():]
        changed_dirs = True

    if new != text:
        with open(cfg_path, "w") as f:
            f.write(new)
    return changed_names, changed_dirs


# ---------------------------------------------------------------- top-level helper
def scaffold_all(spec: ClusterSpec) -> dict:
    """Scaffold the cluster end-to-end (excluding waveform download). Idempotent."""
    src_root = scaffold(spec)
    mod_path = write_cluster_module(spec)
    n_change, d_change = register_cluster(spec)
    return dict(src_root=src_root, module=mod_path,
                names_changed=n_change, src_dirs_changed=d_change)
